### ISSUE TITLE
Not compatible with Umbraco 11?

### ISSUE THREAD

**Issue by ghost** [Joniff/Our.Umbraco.uSync.MemberEdition#2]
Installed on an Umbraco 7 site and seems good - but if I try to install on an Umbraco 11 site, there's no `uSyncBackOffice.Config` file to update? And when I try to run I get:

> System.IO.FileNotFoundException
>   HResult=0x80070002
>   Message=Could not load file or assembly 'Jumoo.uSync.BackOffice, Version=3.1.5.740, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
> <Cannot evaluate the exception stack trace>
>

**Comment by Joniff** [comment]
My original reason for creating this package was for migrating members from Umbraco 7 to 8. In subsequent Umbraco versions Kevin Jump (The creator of uSync) has included a Membership provider (https://jumoo.co.uk/uSync/people/). But as mine was create many years prior I very much doubt the usync files created by this package are compatabile with Kevin's later work.

Sadly I've not played with uSyncPeople but I do note that its looks like its compatable with Umbraco 8, so I could imagine an upgrade path where you use this package to go from Umbraco 7 to 8 and then uSyncPeople from Umbraco 8 to 11, but I wouldn't want to vouch for that.

**Comment by ghost** [comment]
> My original reason for creating this package was for migrating members from Umbraco 7 to 8. In subsequent Umbraco versions Kevin Jump (The creator of uSync) has included a Membership provider (https://jumoo.co.uk/uSync/people/). But as mine was create many years prior I very much doubt the usync files created by this package are compatabile with Kevin's later work.
> 
> Sadly I've not played with uSyncPeople but I do note that its looks like its compatable with Umbraco 8, so I could imagine an upgrade path where you use this package to go from Umbraco 7 to 8 and then uSyncPeople from Umbraco 8 to 11, but I wouldn't want to vouch for that.

That is the conclusion I'd come to as well. Thanks for the well thought out reply @Joniff
